// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJB2-zTS3LE8KkZwS8xir-D4c5Jcljp4',
    appId: '1:854862782149:android:470e8195019ff1dfa75aac',
    messagingSenderId: '854862782149',
    projectId: 'studied-alloy-218011',
    databaseURL: 'https://studied-alloy-218011.firebaseio.com',
    storageBucket: 'studied-alloy-218011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-uWeeYcfRYq7387-n1tcFGb74tulufDY',
    appId: '1:854862782149:ios:dd025bea5f6cf87fa75aac',
    messagingSenderId: '854862782149',
    projectId: 'studied-alloy-218011',
    databaseURL: 'https://studied-alloy-218011.firebaseio.com',
    storageBucket: 'studied-alloy-218011.appspot.com',
    androidClientId:
        '854862782149-5rqpagoulhd3cef5129loruo2e0o59u6.apps.googleusercontent.com',
    iosBundleId: 'com.photory.photoryapp.2024',
  );
}
